# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57844712a094e2b0f49880341952a2572c79491b3c80fad4dcd93212495fefabb68ec97a291ddd14006953f24c641d6a0cc2af181ad816104683dafe1700ff58

test:
  secret_key_base: b53f290c0d93fb54d1f96c596cc2ca7c267c477a3532aae18e2ca61c603425461307b1f8d6af3588529d8df7f125948f7270dff2d2135ceca6bcf46d1f7783ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
